"""create ProductInCart, Topping2ProductInCart

Revision ID: ba77154f75f2
Revises: d3cc16c77435
Create Date: 2023-06-09 22:31:10.327497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba77154f75f2'
down_revision = 'd3cc16c77435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productincart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_phone_number', sa.BigInteger(), nullable=True),
    sa.Column('product_various_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_phone_number'], ['customers.phone_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_various_id'], ['productvarious.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productincart_id'), 'productincart', ['id'], unique=True)
    op.create_table('topping2productincarts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_in_cart_id', sa.Integer(), nullable=True),
    sa.Column('topping_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_in_cart_id'], ['productincart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topping2productincarts_id'), 'topping2productincarts', ['id'], unique=True)
    op.drop_index('ix_toppingtoproducts_id', table_name='topping2orderedproducts')
    op.create_index(op.f('ix_topping2orderedproducts_id'), 'topping2orderedproducts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topping2orderedproducts_id'), table_name='topping2orderedproducts')
    op.create_index('ix_toppingtoproducts_id', 'topping2orderedproducts', ['id'], unique=False)
    op.drop_index(op.f('ix_topping2productincarts_id'), table_name='topping2productincarts')
    op.drop_table('topping2productincarts')
    op.drop_index(op.f('ix_productincart_id'), table_name='productincart')
    op.drop_table('productincart')
    # ### end Alembic commands ###
