"""initial

Revision ID: e1f761f0e1a5
Revises: 
Create Date: 2023-04-17 00:22:03.377962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f761f0e1a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffeehouses',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_coffeehouses_name'), 'coffeehouses', ['name'], unique=False)
    op.create_table('customers',
    sa.Column('phone_number', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_table('fsm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_fsm_id'), 'fsm', ['id'], unique=True)
    op.create_table('productsizes',
    sa.Column('name', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_productsizes_name'), 'productsizes', ['name'], unique=False)
    op.create_table('producttypes',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_producttypes_name'), 'producttypes', ['name'], unique=False)
    op.create_table('blacklist',
    sa.Column('customer', sa.BigInteger(), nullable=False),
    sa.Column('expire', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customers.phone_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer')
    )
    op.create_index(op.f('ix_blacklist_customer'), 'blacklist', ['customer'], unique=False)
    op.create_table('coffeehousebranchs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placement', sa.String(length=20), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coffee_house_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coffee_house_name'], ['coffeehouses.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coffeehousebranchs_id'), 'coffeehousebranchs', ['id'], unique=True)
    op.create_table('logincodes',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('customer_phone_number', sa.BigInteger(), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_phone_number'], ['customers.phone_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_logincodes_code'), 'logincodes', ['code'], unique=False)
    op.create_table('menuupdatetimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('coffee_house_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coffee_house_name'], ['coffeehouses.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menuupdatetimes_id'), 'menuupdatetimes', ['id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=True),
    sa.Column('coffee_house_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coffee_house_name'], ['coffeehouses.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_name'], ['producttypes.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=True)
    op.create_table('toppings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coffee_house_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coffee_house_name'], ['coffeehouses.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toppings_id'), 'toppings', ['id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=3), nullable=True),
    sa.Column('coffee_house_branch_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone_number', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'accepted', 'rejected', 'taken', 'no_taken', 'ready', 'cart', name='orderstatuses'), nullable=True),
    sa.Column('cancel_reason', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['coffee_house_branch_id'], ['coffeehousebranchs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_phone_number'], ['customers.phone_number'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('productvarious',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('size_name', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_name'], ['productsizes.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productvarious_id'), 'productvarious', ['id'], unique=True)
    op.create_table('worktime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee_house_branch_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='daysofweek'), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_house_branch_id'], ['coffeehousebranchs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worktime_id'), 'worktime', ['id'], unique=True)
    op.create_table('orderedproducts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('product_various_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_various_id'], ['productvarious.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderedproducts_id'), 'orderedproducts', ['id'], unique=True)
    op.create_table('toppingtoproducts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordered_product_id', sa.Integer(), nullable=True),
    sa.Column('topping_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordered_product_id'], ['orderedproducts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topping_id'], ['toppings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toppingtoproducts_id'), 'toppingtoproducts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toppingtoproducts_id'), table_name='toppingtoproducts')
    op.drop_table('toppingtoproducts')
    op.drop_index(op.f('ix_orderedproducts_id'), table_name='orderedproducts')
    op.drop_table('orderedproducts')
    op.drop_index(op.f('ix_worktime_id'), table_name='worktime')
    op.drop_table('worktime')
    op.drop_index(op.f('ix_productvarious_id'), table_name='productvarious')
    op.drop_table('productvarious')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_toppings_id'), table_name='toppings')
    op.drop_table('toppings')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_menuupdatetimes_id'), table_name='menuupdatetimes')
    op.drop_table('menuupdatetimes')
    op.drop_index(op.f('ix_logincodes_code'), table_name='logincodes')
    op.drop_table('logincodes')
    op.drop_index(op.f('ix_coffeehousebranchs_id'), table_name='coffeehousebranchs')
    op.drop_table('coffeehousebranchs')
    op.drop_index(op.f('ix_blacklist_customer'), table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_index(op.f('ix_producttypes_name'), table_name='producttypes')
    op.drop_table('producttypes')
    op.drop_index(op.f('ix_productsizes_name'), table_name='productsizes')
    op.drop_table('productsizes')
    op.drop_index(op.f('ix_fsm_id'), table_name='fsm')
    op.drop_table('fsm')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_coffeehouses_name'), table_name='coffeehouses')
    op.drop_table('coffeehouses')
    # ### end Alembic commands ###
